# netlify.toml

[build]
  publish   = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = []
  included_files = []
  # رفع السقف للدوال الثقيلة (اختياري حسب خطتك في نتlify)
  timeout = 30   # أقصى وقت تنفيذ بالثواني
  memory  = 1024 # MB

# إعادة التوجيه للـ API
[[redirects]]
  from = "/api/generate"
  to   = "/.netlify/functions/gemini-proxy"
  status = 200
  force  = true

# تأمين الرؤوس
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
