{
  "name": "netlify-functions",
  "version": "1.0.1",
  "private": true,
  "description": "Serverless functions for Smart Personal Coach (Gemini proxy with fallback/stream/vision/audio).",
  "main": "gemini-proxy.js",
  "type": "commonjs",
  "engines": {
    "node": ">=18.18.0"
  },
  "scripts": {
    "dev": "netlify dev --port=8888",
    "dev:functions": "netlify dev --functions=netlify/functions --port=8888",
    "serve": "netlify dev --port=8888",
    "start": "netlify dev --port=8888",
    "build:functions": "netlify functions:build",
    "test": "node -e \"console.log('OK')\""
  },
  "dependencies": {
    "dotenv": "^16.4.5"
  },
  "devDependencies": {
    "netlify-cli": "^17.34.1"
  }
}
