# ===================== موجود لديك كما هو =====================
[build]
  publish   = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

# API ↔︎ Function
[[redirects]]
  from = "/api/generate"
  to   = "/.netlify/functions/gemini-proxy"
  status = 200
  force  = true

# Admin route ↔︎ static file
[[redirects]]
  from = "/admin"
  to   = "/admin/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# جلسة جديدة لكل مستخدم
[[redirects]]
  from = "/api/create-session"
  to   = "/.netlify/functions/create-session"
  status = 200
  force  = true

# إرسال/جلب رسائل جلسة واحدة
[[redirects]]
  from = "/api/chat"
  to   = "/.netlify/functions/chat"
  status = 200
  force  = true

# ===================== إضافات اختيارية (Append Only) =====================

# لو فتحت روابط فرعية داخل /admin (بدون راوتر) خليك على نفس الملف
[[redirects]]
  from = "/admin/*"
  to   = "/admin/index.html"
  status = 200

# مسارات قصيرة للدوال الجديدة (تقدر تظل تستخدم /.netlify/functions/* إن حبيت)
[[redirects]]
  from = "/api/adminless/upsert-session"
  to   = "/.netlify/functions/adminless-upsert-session"
  status = 200
  force  = true

[[redirects]]
  from = "/api/adminless/add-message"
  to   = "/.netlify/functions/adminless-add-message"
  status = 200
  force  = true

# كاش ثابت لأي أصول ثابتة (لو عندك مجلد assets مثلاً)
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# إبراز متغيرات البيئة في إعدادات Netlify (تذكير فقط، القيم توضع من لوحة Netlify)
[template.environment]
  GEMINI_API_KEY = "your-gemini-key"
  SUPABASE_URL = "https://xxxx.supabase.co"
  SUPABASE_SERVICE_ROLE_KEY = "your-service-role-key"
