# netlify.toml

[build]
  publish   = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

# API ↔︎ Function
[[redirects]]
  from = "/api/generate"
  to   = "/.netlify/functions/gemini-proxy"
  status = 200
  force  = true

# Admin route ↔︎ static file
[[redirects]]
  from = "/admin"
  to   = "/admin/index.html"
  status = 200

# (اختياري) لو أردت أن كل الروابط الفرعية تحت /admin/* تفتح نفس الملف
# [[redirects]]
#   from = "/admin/*"
#   to   = "/admin/index.html"
#   status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
